name: ankidroid_for_flutter_example
description: Demonstrates how to use the ankidroid_for_flutter plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ankidroid_for_flutter:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
