name: ankidroid_for_flutter
description: A flutter wrapper over the java AnkiDroid API.
version: 1.0.0
repository: https://github.com/captaindario/ankidroid_for_flutter/

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.captaindario.ankidroid_for_flutter
        pluginClass: AnkidroidForFlutterPlugin
